server:
  port: 8090

# config resilience4j reactor

resilience4j:
  circuitbreaker:
    configs:
      example:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      products:
        base-config: example
  timelimiter:
    configs:
      example:
        timeout-duration: 2s
    instances:
      products:
        base-config: example

spring:
  application:
    name: service-gateway-server
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
      instance:
        prefer-ip-address: true
#  config:
#    import: "optional:configserver:"
  cloud:
    gateway:
      routes:
        - id: service-products
          uri: lb://SERVICE-PRODUCTS
          predicates:
            - Path=/api/serviceProducts/**
#            - Header= token, \d+
#            - Header= Content-Type,application/json
#            - Method= GET, POST
#            - Query=color
#            - Cookie=color, azul
          filters:
            - name: CircuitBreaker
              args:
                name: products
                statusCode: 500
                fallbackUri: forward:/api/serviceItems/9/amount/5
            - StripPrefix=2
            - ExampleCookie=hola este es mi mensaje personalizado, usuario, PepitoGrillo
#            - name: Example
#              args:
#                message: hola este es mi mensaje personalizado
#                cookieName: usuario
#                cookieValue: PepitoGrillo
          metadata:
            ribbon:
              enabled: false
        - id: service-items
          uri: lb://SERVICE-ITEMS
          predicates:
            - Path=/api/serviceItems/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request,123456Req
            - AddResponseHeader=token-response,123456Res
            - AddRequestParameter=name, Pepillo
          metadata:
            ribbon:
              enabled: false
        - id: service-users
          uri: lb://SERVICE-USERS
          predicates:
            - Path=/api/serviceUsers/**
          filters:
            - StripPrefix=2
        - id: service-oauth
          uri: lb://SERVICE-OAUTH
          predicates:
            - Path=/api/serviceOauth/**
          filters:
            - StripPrefix=2

